import type { Property } from './types';

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Modern Villa in the Hills',
    description: 'A stunning modern villa offering panoramic views of the city. Features an infinity pool and state-of-the-art amenities.',
    price: 3500000,
    location: 'Los Angeles, CA',
    beds: 5,
    baths: 6,
    sqft: 6200,
    imageIds: ['property-1-1', 'property-1-2'],
    features: ['Infinity Pool', 'Home Theater', 'Smart Home System', 'City Views'],
  },
  {
    id: 'p2',
    title: 'Chic Downtown Penthouse',
    description: 'An exclusive penthouse in the heart of downtown. Floor-to-ceiling windows provide breathtaking skyline views.',
    price: 5200000,
    location: 'New York, NY',
    beds: 3,
    baths: 4,
    sqft: 4100,
    imageIds: ['property-2-1', 'property-2-2'],
    features: ['Rooftop Terrace', '24/7 Concierge', 'Private Elevator', 'Skyline Views'],
  },
  {
    id: 'p3',
    title: 'Secluded Countryside Mansion',
    description: 'A grand mansion set on 50 acres of pristine countryside. A perfect escape with ultimate privacy and luxury.',
    price: 8900000,
    location: 'Aspen, CO',
    beds: 8,
    baths: 10,
    sqft: 12500,
    imageIds: ['property-3-1'],
    features: ['Private Lake', 'Equestrian Facilities', 'Vineyard', 'Guest House'],
  },
  {
    id: 'p4',
    title: 'Oceanfront Paradise',
    description: 'Wake up to the sound of waves in this beautiful beachfront property. Direct access to a private beach.',
    price: 6750000,
    location: 'Miami, FL',
    beds: 4,
    baths: 5,
    sqft: 5500,
    imageIds: ['property-4-1'],
    features: ['Private Beach Access', 'Ocean Views', 'Outdoor Kitchen', 'Yacht Dock'],
  },
  {
    id: 'p5',
    title: 'Industrial Modern Loft',
    description: 'A unique loft in a converted factory, featuring exposed brick, high ceilings, and a massive open-plan living space.',
    price: 2100000,
    location: 'Chicago, IL',
    beds: 2,
    baths: 2,
    sqft: 3200,
    imageIds: ['property-5-1'],
    features: ['High Ceilings', 'Exposed Brick', 'Open Concept', 'Artist Studio'],
  },
  {
    id: 'p6',
    title: 'Rustic Mountain Retreat',
    description: 'A cozy yet luxurious cabin perfect for ski lovers and nature enthusiasts. Features a large stone fireplace and mountain views.',
    price: 1850000,
    location: 'Jackson Hole, WY',
    beds: 4,
    baths: 3,
    sqft: 3800,
    imageIds: ['property-6-1'],
    features: ['Ski-in/Ski-out', 'Mountain Views', 'Hot Tub', 'Stone Fireplace'],
  },
   {
    id: 'p7',
    title: 'Luxury High-Rise Apartment',
    description: 'Sophisticated living in a modern high-rise, complete with a residents-only lounge and fitness center.',
    price: 2750000,
    location: 'San Francisco, CA',
    beds: 2,
    baths: 3,
    sqft: 2100,
    imageIds: ['property-7-1'],
    features: ['City Views', 'Valet Parking', 'Fitness Center', 'Resident Lounge'],
  },
  {
    id: 'p8',
    title: 'Elegant Suburban Family Home',
    description: 'A beautiful family home in a quiet, upscale suburb, featuring a large backyard and a designer kitchen.',
    price: 1500000,
    location: 'Austin, TX',
    beds: 5,
    baths: 4,
    sqft: 4500,
    imageIds: ['property-8-1'],
    features: ['Gourmet Kitchen', 'Large Backyard', 'Community Pool', 'Top School District'],
  },
  {
    id: 'p9',
    title: 'Historic Townhouse Gem',
    description: 'A meticulously restored historic townhouse that blends timeless elegance with modern comforts.',
    price: 3200000,
    location: 'Boston, MA',
    beds: 4,
    baths: 4,
    sqft: 3900,
    imageIds: ['property-9-1'],
    features: ['Historic Architecture', 'Private Garden', 'Rooftop Deck', 'Modern Renovation'],
  },
   {
    id: 'p10',
    title: 'Sustainable Eco-Haven',
    description: 'An architectural masterpiece of sustainable design, powered by solar and built with reclaimed materials.',
    price: 4100000,
    location: 'Portland, OR',
    beds: 3,
    baths: 3,
    sqft: 3500,
    imageIds: ['property-10-1'],
    features: ['Eco-Friendly', 'Solar Panels', 'Green Roof', 'Rainwater Harvesting'],
  },
];
