import type { Property, Testimonial } from './types';

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Modern Villa in the Hills',
    description: 'Nestled in the serene hills overlooking the vibrant expanse of Los Angeles, this modern architectural masterpiece offers an unparalleled living experience. The residence is a testament to sophisticated design, blending sleek lines with organic textures to create a space that is both visually stunning and profoundly calming. As you step inside, you are greeted by an expansive open-concept living area, where floor-to-ceiling glass walls frame breathtaking panoramic views of the city skyline. The seamless transition from indoor to outdoor living is exemplified by the infinity pool, which appears to merge with the horizon. Every detail has been meticulously curated, from the smart home system that offers effortless control over your environment, to the private home theater that provides a cinematic experience. This villa is not just a residence; it\'s a statement of luxury and a sanctuary above the city.',
    price: 3500000,
    location: 'Los Angeles, CA',
    beds: 5,
    baths: 6,
    sqft: 6200,
    imageIds: ['property-1-1', 'property-1-2'],
    features: ['Infinity Pool', 'Home Theater', 'Smart Home System', 'City Views'],
  },
  {
    id: 'p2',
    title: 'Chic Downtown Penthouse',
    description: 'Perched atop one of New York\'s most prestigious skyscrapers, this chic downtown penthouse represents the zenith of urban luxury. Offering an exclusive retreat from the bustling city below, this residence is a sanctuary of style and sophistication. Upon entering via a private, key-coded elevator, you are immediately enveloped by an atmosphere of refined elegance. The sprawling living space is defined by its dramatic floor-to-ceiling windows, which offer 360-degree, jaw-dropping views of the iconic Manhattan skyline. Step out onto the expansive rooftop terrace, a rare urban oasis perfect for al fresco dining or simply watching the city lights twinkle to life. With 24/7 concierge service anticipating your every need, this penthouse is more than a home—it is a lifestyle statement for the discerning individual who demands nothing but the best in the heart of the city that never sleeps.',
    price: 5200000,
    location: 'New York, NY',
    beds: 3,
    baths: 4,
    sqft: 4100,
    imageIds: ['property-2-1', 'property-2-2'],
    features: ['Rooftop Terrace', '24/7 Concierge', 'Private Elevator', 'Skyline Views'],
  },
  {
    id: 'p4',
    title: 'Oceanfront Paradise',
    description: 'Experience the ultimate coastal lifestyle in this exquisite oceanfront paradise, where the turquoise waters of Miami are your backyard. This stunning property offers a rare opportunity to live directly on the sand, with private, gated access to a pristine stretch of beach. From the moment you enter, you are captivated by the panoramic ocean views that fill every room through walls of glass. The interior design is a seamless blend of contemporary comfort and beach-chic, with an open floor plan that encourages a relaxed flow. Wake up to the gentle sound of waves lapping the shore in your serene master suite, which features a private balcony perfect for morning coffee. The expansive outdoor living area is an entertainer\'s dream, complete with a sparkling pool and a fully equipped outdoor kitchen. For the boating enthusiast, a private yacht dock provides immediate access to the open water. This is a sensory experience, a place where every day feels like a vacation.',
    price: 6750000,
    location: 'Miami, FL',
    beds: 4,
    baths: 5,
    sqft: 5500,
    imageIds: ['property-4-1'],
    features: ['Private Beach Access', 'Ocean Views', 'Outdoor Kitchen', 'Yacht Dock'],
  },
  {
    id: 'p5',
    title: 'Industrial Modern Loft',
    description: 'Discover a truly unique living experience in this spectacular industrial modern loft, located within a meticulously restored factory in the heart of Chicago\'s most vibrant neighborhood. This residence is a celebration of history and contemporary design, offering a dramatic and inspiring space. The moment you step inside, you are struck by the sheer volume of the massive open-plan living area, defined by soaring 20-foot ceilings, original exposed brick walls, and massive timber beams that speak to the building\'s industrial heritage. Sunlight pours through enormous factory windows, illuminating the polished concrete floors. The space is perfect for both large-scale entertaining and quiet contemplation. A dedicated artist studio with ample natural light provides the ideal environment for creative pursuits. This is a rare opportunity to own a piece of Chicago history, reimagined for the ultimate in modern urban living.',
    price: 2100000,
    location: 'Chicago, IL',
    beds: 2,
    baths: 2,
    sqft: 3200,
    imageIds: ['property-5-1'],
    features: ['High Ceilings', 'Exposed Brick', 'Open Concept', 'Artist Studio'],
  },
  {
    id: 'p7',
    title: 'Luxury High-Rise Apartment',
    description: 'Elevate your lifestyle in this sophisticated high-rise apartment, offering a premier address in the vibrant heart of San Francisco. This residence combines breathtaking city views with an array of exclusive, five-star amenities designed for modern urban living. The open-concept living space is bathed in natural light, with floor-to-ceiling windows that showcase panoramic vistas of the city and the bay. The sleek, modern kitchen is equipped with high-end integrated appliances and designer finishes. As a resident, you will enjoy exclusive access to a state-of-the-art fitness center, a beautifully appointed resident lounge perfect for socializing or working from home, and the convenience of 24-hour valet parking and concierge service. This is turnkey luxury living at its finest, providing a secure and comfortable sanctuary with the best of San Francisco\'s dining, shopping, and cultural attractions just moments away.',
    price: 2750000,
    location: 'San Francisco, CA',
    beds: 2,
    baths: 3,
    sqft: 2100,
    imageIds: ['property-7-1'],
    features: ['City Views', 'Valet Parking', 'Fitness Center', 'Resident Lounge'],
  },
  {
    id: 'p11',
    title: 'SoHo Artist Loft',
    description: 'A sprawling loft in the heart of SoHo, this space is a blank canvas for your creative vision. With original tin ceilings, vast open space, and oversized windows that flood the apartment with light, it’s an inspiring home for artists and collectors alike. The custom chef\'s kitchen is an entertainer\'s dream, and the flexible layout allows for multiple living and working configurations. Located in a historic cast-iron building, you are steps away from world-class galleries, boutiques, and dining. This is authentic loft living at its finest, a rare find in one of Manhattan’s most desirable neighborhoods.',
    price: 4800000,
    location: 'New York, NY',
    beds: 2,
    baths: 3,
    sqft: 3500,
    imageIds: ['property-11-1'],
    features: ['Original Details', 'Chef\'s Kitchen', 'Cast-Iron Building', 'Open Layout'],
  },
  {
    id: 'p12',
    title: 'Classic Upper East Side Townhouse',
    description: 'Experience timeless New York elegance in this masterfully renovated townhouse on a tree-lined street in the Upper East Side. This home seamlessly blends classic architectural details with modern luxury. Featuring a grand stoop entrance, a formal dining room with a fireplace, a private garden, and a full-floor master suite with a spa-like bathroom. The home has been updated with smart home technology, a new elevator, and a custom kitchen. It\'s an oasis of tranquility and sophistication, located just blocks from Central Park and the city’s finest museums and schools.',
    price: 12500000,
    location: 'New York, NY',
    beds: 6,
    baths: 7,
    sqft: 7200,
    imageIds: ['property-12-1'],
    features: ['Private Garden', 'Gourmet Kitchen', 'Elevator', 'Prime Location'],
  },
  {
    id: 'p13',
    title: 'Hollywood Hills View Estate',
    description: 'This stunning contemporary home in the coveted Hollywood Hills offers breathtaking views from downtown to the ocean. The property features an open floor plan with disappearing glass walls for seamless indoor-outdoor living. The backyard is an entertainer\'s paradise with an infinity pool, spa, and outdoor kitchen. The master suite is a luxurious retreat with a fireplace, private balcony, and a spa-like bathroom with a soaking tub overlooking the city. A state-of-the-art screening room and a temperature-controlled wine cellar complete this exceptional offering. Live the quintessential LA lifestyle in this architectural gem.',
    price: 7950000,
    location: 'Los Angeles, CA',
    beds: 5,
    baths: 6,
    sqft: 5800,
    imageIds: ['property-13-1'],
    features: ['Infinity Pool', 'Screening Room', 'Wine Cellar', 'Panoramic Views'],
  },
  {
    id: 'p14',
    title: 'Beverly Hills Mediterranean Villa',
    description: 'Located north of Sunset Boulevard in the heart of Beverly Hills, this exquisite Mediterranean villa offers privacy, luxury, and timeless style. Enter through private gates to a grand motor court and beautifully landscaped grounds. The interiors are voluminous and filled with natural light, featuring high ceilings, arched doorways, and fine finishes. The gourmet kitchen opens to a family room and breakfast area overlooking the lush backyard. The outdoor space includes a large pool, spa, and a cabana with a fireplace. This is a rare opportunity to own a significant estate in one of the world\'s most exclusive neighborhoods.',
    price: 18000000,
    location: 'Los Angeles, CA',
    beds: 7,
    baths: 9,
    sqft: 11000,
    imageIds: ['property-14-1'],
    features: ['Gated Estate', 'Motor Court', 'Swimming Pool', 'Lush Gardens'],
  },
  {
    id: 'p15',
    title: 'Pacific Heights Grand Victorian',
    description: 'An architectural masterpiece, this grand Victorian home in Pacific Heights has been exquisitely restored, preserving its historic details while offering all the amenities for modern living. The home boasts intricate woodwork, soaring ceilings, and stunning period details throughout. The formal living and dining rooms are perfect for entertaining, while the modern, light-filled kitchen and family room open to a landscaped garden. The top floor features a pent-room and a roof deck with panoramic views of the Golden Gate Bridge and the Bay. This is a rare opportunity to own a piece of San Francisco history.',
    price: 9750000,
    location: 'San Francisco, CA',
    beds: 6,
    baths: 5,
    sqft: 6500,
    imageIds: ['property-15-1'],
    features: ['Historic Details', 'Bay Views', 'Landscaped Garden', 'Roof Deck'],
  },
  {
    id: 'p16',
    title: 'Sleek SoMa Loft with Private Deck',
    description: 'Embrace the vibrant SoMa lifestyle in this sleek, contemporary loft. This two-level residence features an open-concept living area with double-height ceilings, polished concrete floors, and a wall of windows that floods the space with natural light. The modern kitchen is equipped with high-end appliances and custom cabinetry. A floating staircase leads to the mezzanine bedroom overlooking the living area below. The highlight of this property is the large, private deck, perfect for indoor-outdoor living and entertaining. Located in a boutique elevator building, you are just moments from trendy restaurants, art galleries, and tech hubs.',
    price: 1950000,
    location: 'San Francisco, CA',
    beds: 1,
    baths: 2,
    sqft: 1800,
    imageIds: ['property-16-1'],
    features: ['Two Levels', 'Private Deck', 'Double-Height Ceilings', 'Concrete Floors'],
  },
  {
    id: 'p17',
    title: 'Lincoln Park Greystone Mansion',
    description: 'An iconic Lincoln Park greystone, this magnificent mansion has been completely renovated to the highest standards. The grand foyer with a sweeping staircase welcomes you into a home of unparalleled elegance. The main level features expansive living and dining rooms, a custom-built library, and a stunning gourmet kitchen that opens to a beautifully landscaped backyard and a heated, attached garage. The upper levels offer luxurious bedroom suites, including a full-floor master retreat with a lavish spa bath. The lower level includes a home theater, gym, and wine cellar. A true Chicago masterpiece, just steps from the park and lake.',
    price: 11500000,
    location: 'Chicago, IL',
    beds: 7,
    baths: 8,
    sqft: 10000,
    imageIds: ['property-17-1'],
    features: ['Greystone Architecture', 'Home Theater', 'Landscaped Yard', 'Attached Garage'],
  },
  {
    id: 'p18',
    title: 'River North Penthouse with Lake Views',
    description: 'Soaring above the city in a premier River North tower, this stunning penthouse offers unobstructed, panoramic views of Lake Michigan and the Chicago skyline from every room. This full-floor residence was designed for sophisticated entertaining and comfortable living. An open floor plan features a spacious living room with a fireplace, a formal dining area, and a gourmet kitchen with top-of-the-line appliances. The master suite is a serene oasis with a spa-like bath and custom walk-in closets. Building amenities include a 24-hour doorman, fitness center, and indoor pool. A truly exceptional residence in the sky.',
    price: 6500000,
    location: 'Chicago, IL',
    beds: 4,
    baths: 5,
    sqft: 5200,
    imageIds: ['property-18-1'],
    features: ['Lake Views', 'Full-Floor Residence', '24-Hour Doorman', 'Indoor Pool'],
  },
  {
    id: 'p19',
    title: 'Venetian Islands Waterfront Modern',
    description: 'A stunning example of modern waterfront architecture on Miami\'s exclusive Venetian Islands. This home offers wide bay views and the ultimate indoor-outdoor lifestyle. The sleek, open-plan interior features floor-to-ceiling glass, Italian porcelain floors, and a gourmet kitchen by Boffi. The expansive outdoor area includes an infinity-edge pool, a summer kitchen, and a private dock with a boat lift. The master suite upstairs boasts a private terrace and a luxurious bathroom with a steam shower. This is a boater\'s paradise and an entertainer\'s dream, just minutes from South Beach and downtown Miami.',
    price: 15500000,
    location: 'Miami, FL',
    beds: 6,
    baths: 7,
    sqft: 7500,
    imageIds: ['property-19-1'],
    features: ['Waterfront', 'Private Dock', 'Infinity Pool', 'Bay Views'],
  },
  {
    id: 'p20',
    title: 'South of Fifth Luxury Condo',
    description: 'Located in the prestigious South of Fifth neighborhood, this flow-through residence in a five-star oceanfront building offers breathtaking direct ocean and city views. A private elevator foyer leads into a spacious living area with expansive terraces on both the east and west sides, perfect for watching the sunrise over the ocean and the sunset over the city. The condo features a custom Italian kitchen, marble floors, and smart home automation. Residents enjoy access to a private beach club, multiple pools, a world-class spa and fitness center, and 24-hour concierge and valet services. The pinnacle of luxury beachfront living.',
    price: 9200000,
    location: 'Miami, FL',
    beds: 3,
    baths: 4,
    sqft: 4100,
    imageIds: ['property-20-1'],
    features: ['Oceanfront', 'Private Elevator', 'Multiple Terraces', '5-Star Amenities'],
  },
  {
    id: 'p21',
    title: 'Georgetown Federal Townhouse',
    description: 'A quintessential Georgetown classic, this historic Federal townhouse has been impeccably renovated, combining timeless charm with modern luxury. The elegant main level is perfect for entertaining, with a formal living room, dining room with fireplace, and a chef\'s kitchen that opens onto a deep, private garden and terrace. The upper levels offer spacious bedrooms with en-suite baths. The lower level provides flexible space for a family room or guest suite. Located on one of Georgetown\'s most sought-after cobblestone streets, this home is just steps from the best shops, restaurants, and the waterfront.',
    price: 4995000,
    location: 'Washington, DC',
    beds: 5,
    baths: 5,
    sqft: 4800,
    imageIds: ['property-21-1'],
    features: ['Historic Federal Style', 'Private Garden', 'Chef\'s Kitchen', 'Cobblestone Street'],
  },
  {
    id: 'p22',
    title: 'Modern Logan Circle Penthouse',
    description: 'This stunning two-level penthouse in the heart of Logan Circle offers incredible city views and luxurious finishes. An open-concept living space features a gourmet kitchen with designer appliances, a spacious living area with a fireplace, and a wall of windows leading to a private terrace. The upper level is dedicated to a magnificent master suite with a spa-like bathroom and a huge walk-in closet. A private roof deck offers panoramic views of the city, including the Washington Monument, and is perfect for entertaining. The boutique building is just steps from the vibrant 14th Street corridor.',
    price: 2850000,
    location: 'Washington, DC',
    beds: 3,
    baths: 3,
    sqft: 2600,
    imageIds: ['property-22-1'],
    features: ['Private Roof Deck', 'Two Levels', 'City Views', 'Designer Finishes'],
  },
  {
    id: 'p23',
    title: 'La Jolla Oceanfront Estate',
    description: 'Perched on a dramatic ocean bluff in La Jolla, this spectacular estate offers unparalleled white-water views and luxurious coastal living. The property has been beautifully designed to maximize its stunning setting, with floor-to-ceiling windows and expansive terraces. The main level features a grand living room, a formal dining room, and a gourmet kitchen, all with ocean views. The master suite is a private retreat with its own fireplace, balcony, and spa bath. An infinity-edge pool seems to spill directly into the Pacific Ocean below. Direct, private access to a secluded beach makes this a truly one-of-a-kind property.',
    price: 22000000,
    location: 'San Diego, CA',
    beds: 5,
    baths: 7,
    sqft: 8000,
    imageIds: ['property-23-1'],
    features: ['Oceanfront Bluff', 'Infinity Pool', 'Private Beach Access', 'White-Water Views'],
  },
  {
    id: 'p24',
    title: 'Coronado Beach House',
    description: 'The epitome of Southern California beach living, this charming yet sophisticated home is located just steps from the pristine sands of Coronado Beach. The home features a bright and airy open floor plan, with a comfortable living room that opens onto a spacious front porch. The gourmet kitchen is perfect for family gatherings. The upstairs master suite includes a private balcony with ocean breezes. The backyard features a built-in BBQ and a fire pit, creating an ideal space for evening entertaining after a day at the beach. This is a rare opportunity to own a home in one of San Diego\'s most iconic and desirable beach communities.',
    price: 6300000,
    location: 'San Diego, CA',
    beds: 4,
    baths: 4,
    sqft: 3200,
    imageIds: ['property-24-1'],
    features: ['Steps to Beach', 'Ocean Breezes', 'Front Porch', 'Backyard with Fire Pit'],
  },
  {
    id: 'p25',
    title: 'Malibu Beachfront Contemporary',
    description: 'Wake up to the sound of the waves in this stunning contemporary home on the sands of Malibu. This architectural gem features walls of glass that open to expansive decks, blurring the line between indoors and out. With direct beach access, an open-concept living space, and a state-of-the-art kitchen, it is the perfect place for both relaxing and entertaining. The master suite offers panoramic ocean views, a private balcony, and a spa-like bathroom. Enjoy breathtaking sunsets from the comfort of your living room. This is the ultimate California dream home, offering a lifestyle of luxury and tranquility.',
    price: 14500000,
    location: 'Los Angeles, CA',
    beds: 4,
    baths: 5,
    sqft: 4500,
    imageIds: ['property-25-1'],
    features: ['Direct Beach Access', 'Ocean Views', 'Expansive Decks', 'Gourmet Kitchen'],
  },
  {
    id: 'p26',
    title: 'Tribeca Penthouse Loft',
    description: 'This extraordinary duplex penthouse loft in a landmarked Tribeca building is a masterpiece of design. The great room features soaring ceilings, a wood-burning fireplace, and massive skylights. The custom Bulthaup kitchen is a chef\'s dream. A dramatic steel and glass staircase leads to the upper level, which includes the master suite and access to a spectacular private roof terrace with stunning city views, an outdoor kitchen, and a hot tub. With authentic details and modern luxuries, this is one of the most magnificent private residences in downtown Manhattan.',
    price: 19950000,
    location: 'New York, NY',
    beds: 5,
    baths: 6,
    sqft: 6800,
    imageIds: ['property-26-1'],
    features: ['Duplex Penthouse', 'Private Roof Terrace', 'Wood-Burning Fireplace', 'Landmarked Building'],
  },
  {
    id: 'p27',
    title: 'Fisher Island Waterfront Condo',
    description: 'Live an exclusive island lifestyle in this magnificent waterfront condominium on the prestigious Fisher Island. This residence offers panoramic views of the Atlantic Ocean and the Miami skyline. The expansive unit features marble floors, a gourmet kitchen, and spacious terraces for enjoying the ocean breeze. Residents have access to the island\'s world-class amenities, including a private beach, golf course, tennis courts, spa, and multiple fine dining restaurants. Fisher Island is accessible only by ferry or private yacht, ensuring the utmost privacy and security. This is a rare opportunity to live in one of the most exclusive communities in the world.',
    price: 12900000,
    location: 'Miami, FL',
    beds: 4,
    baths: 5,
    sqft: 5600,
    imageIds: ['property-27-1'],
    features: ['Exclusive Island', 'Ocean & City Views', 'Private Beach', 'Golf Course'],
  },
  {
    id: 'p28',
    title: 'Gold Coast Historic Mansion',
    description: 'This stately and magnificent historic mansion on Chicago\'s prestigious Gold Coast has been restored to perfection. The home offers grand-scale rooms for entertaining, including a formal living room, a handsome library, and an elegant dining room. The incredible chef\'s kitchen and great room overlook a beautifully landscaped private garden. The home features multiple fireplaces, intricate millwork, and an elevator. The full-floor master suite is a luxurious sanctuary. This is an opportunity to own a piece of Chicago history in one of its most desirable neighborhoods, just steps from Lake Michigan and Magnificent Mile.',
    price: 9750000,
    location: 'Chicago, IL',
    beds: 6,
    baths: 7,
    sqft: 9500,
    imageIds: ['property-28-1'],
    features: ['Historic Gold Coast', 'Restored Mansion', 'Private Garden', 'Chef\'s Kitchen'],
  },
  {
    id: 'p29',
    title: 'Nob Hill Classic Residence',
    description: 'Located in a premier pre-war cooperative building in the heart of Nob Hill, this elegant apartment offers stunning views of Huntington Park and Grace Cathedral. The grand-scale rooms are perfect for entertaining, with a formal living room, dining room, and a wood-paneled library. The residence features high ceilings, beautiful hardwood floors, and classic architectural details. The building offers 24-hour doorman service and professional management. This is a rare opportunity to live in one of San Francisco\'s most iconic and sought-after buildings, with the best of the city at your doorstep.',
    price: 5900000,
    location: 'San Francisco, CA',
    beds: 3,
    baths: 4,
    sqft: 3800,
    imageIds: ['property-29-1'],
    features: ['Premier Coop Building', 'Park Views', '24-Hour Doorman', 'Classic Architecture'],
  },
  {
    id: 'p30',
    title: 'Kalorama Grand Townhome',
    description: 'This magnificent and grand townhome in the prestigious Kalorama neighborhood has hosted presidents and diplomats. The impressive limestone facade welcomes you to a home of unparalleled scale and elegance. The main level features a grand receiving salon, a formal dining room that can seat 20, and a commercial-grade kitchen. The upper levels offer luxurious bedroom suites. The home also includes an elevator, a wine cellar, and a spacious rear garden and terrace for entertaining. Located on a beautiful tree-lined street, this is one of Washington D.C.\'s most significant private residences.',
    price: 16000000,
    location: 'Washington, DC',
    beds: 8,
    baths: 10,
    sqft: 12000,
    imageIds: ['property-30-1'],
    features: ['Limestone Facade', 'Grand-Scale Rooms', 'Commercial-Grade Kitchen', 'Private Garden'],
  },
  {
    id: 'p31',
    title: 'Point Loma Modern with Bay Views',
    description: 'This brand new modern masterpiece in Point Loma offers breathtaking, panoramic views of the San Diego Bay and city skyline. The home features an open-concept floor plan with soaring ceilings and walls of glass that disappear, creating a seamless indoor-outdoor flow. The gourmet kitchen boasts top-of-the-line appliances and a massive island. The master suite is a true retreat with a private deck, fireplace, and a spa-like bathroom. The backyard is an entertainer\'s dream with an infinity pool, spa, and built-in BBQ. This is an architectural marvel in one of San Diego\'s most desirable neighborhoods.',
    price: 8500000,
    location: 'San Diego, CA',
    beds: 5,
    baths: 6,
    sqft: 6000,
    imageIds: ['property-31-1'],
    features: ['Bay & City Views', 'Infinity Pool', 'Indoor-Outdoor Flow', 'Gourmet Kitchen'],
  },
  {
    id: 'p32',
    title: 'Del Mar Beach Colony Home',
    description: 'Located in the highly sought-after Del Mar Beach Colony, this stunning coastal home is just steps from the sand. The home has been beautifully remodeled with a modern beach aesthetic, featuring an open-concept living space, a gourmet kitchen, and disappearing pocket doors that lead to a private backyard with a spa and fire pit. The master suite offers a private balcony with ocean views. This is the perfect home for enjoying the relaxed, yet sophisticated, Del Mar lifestyle, with world-class dining and shopping just a short walk away. An exceptional opportunity to live your dream at the beach.',
    price: 7200000,
    location: 'San Diego, CA',
    beds: 4,
    baths: 4,
    sqft: 3500,
    imageIds: ['property-32-1'],
    features: ['Steps to Beach', 'Ocean Views', 'Remodeled', 'Private Backyard'],
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah L.',
    location: 'New York, NY',
    quote: 'Rahman Estates made finding our dream penthouse a reality. The AI recommendations were scarily accurate, and the entire process was seamless. Truly a first-class experience.',
    imageId: 'testimonial-1',
  },
  {
    id: 't2',
    name: 'James & Emily T.',
    location: 'Los Angeles, CA',
    quote: "The level of detail and personalization is unmatched. We felt understood and catered to from day one. Their curated listings saved us so much time. We couldn't be happier with our new home.",
    imageId: 'testimonial-2',
  },
  {
    id: 't3',
    name: 'Kenji Tanaka',
    location: 'Miami, FL',
    quote: "As an international buyer, I needed a team I could trust. Rahman Estates exceeded all expectations. Professional, discreet, and incredibly knowledgeable about the luxury market.",
    imageId: 'testimonial-3',
  },
  {
    id: 't4',
    name: 'Olivia Chen',
    location: 'Aspen, CO',
    quote: "From sprawling estates to exclusive penthouses, their portfolio is breathtaking. The virtual tours are so immersive. Found our perfect mountain retreat without leaving our home!",
    imageId: 'testimonial-4',
  }
];
